bot:
  token: ${TOKEN}
  defaultPrefix: fb!

database:
  url: ${DATABASE_URL}

extensions:
  # everything you load lives under the cogs/ package
  cogs:
    BotGuildSettings: { enabled: false }
    BotSettings:      { enabled: false }
    Den:              { enabled: false }
    Dexter:           { enabled: false }
    fc:               { enabled: false }
    FunCommands:      { enabled: false }
    functions:        { enabled: false }
    petting:          { enabled: false }
    reactrole:        { enabled: false }
    Birthday:         { enabled: false }
